"""Pydantic v2 models for Constitutional AI rules engine."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Literal, Any
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator, ConfigDict


class Priority(str, Enum):
    """Priority levels for rules."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Enforcement(str, Enum):
    """Enforcement strategies for hard rules."""
    BLOCK_IF_VIOLATED = "block_if_violated"
    WARN_IF_VIOLATED = "warn_if_violated"


class ResponseType(str, Enum):
    """Types of responses that can be evaluated by rules."""
    RESEARCH_FINDING = "research_finding"
    SYNTHESIS = "synthesis"
    TOOL_CALL = "tool_call"
    REASONING = "reasoning"
    GENERAL = "general"


class Rule(BaseModel):
    """Base rule model (abstract)."""
    model_config = ConfigDict(validate_assignment=True)

    id: str = Field(..., min_length=1, max_length=10, description="Unique rule ID")
    rule: str = Field(..., min_length=10, description="Rule statement")
    rationale: str = Field(default="", description="Why this rule exists")
    priority: Priority = Field(default=Priority.MEDIUM, description="Rule priority")

    @field_validator("id")
    @classmethod
    def validate_id_format(cls, v: str) -> str:
        """Ensure ID is properly formatted (e.g., H1, S2, L3)."""
        if not (len(v) in [2, 3] and v[0].isalpha() and v[1:].isdigit()):
            raise ValueError(f"Invalid rule ID format: {v}")
        return v


class HardRule(Rule):
    """Hard rule: agent cannot modify, must enforce."""

    enforcement: Enforcement = Field(
        default=Enforcement.BLOCK_IF_VIOLATED,
        description="How to enforce this rule"
    )
    immutable: bool = Field(default=True, description="Cannot be modified by agent")


class SoftRule(Rule):
    """Soft rule: agent can propose improvements based on learning."""

    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in rule effectiveness [0,1]"
    )
    effectiveness_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Historical effectiveness score"
    )
    derived_from: str | None = Field(
        default=None,
        description="Task UUID this rule was derived from"
    )


class MetaRule(Rule):
    """Meta-rules: how to apply rules when they conflict."""
    pass


class LearningRule(Rule):
    """Learning rule: generated by agent from observed failures."""

    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in rule effectiveness [0,1]"
    )
    effectiveness_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Will be updated after A/B testing"
    )
    derived_from: str = Field(
        ...,
        description="Task UUID this rule was derived from"
    )
    failure_case: str = Field(
        default="",
        description="Example failure case this rule addresses"
    )


class Critique(BaseModel):
    """LLM critique of whether a response violates a rule."""
    model_config = ConfigDict(validate_assignment=True)

    rule_id: str = Field(..., description="ID of the rule being critiqued")
    violates: bool = Field(..., description="Does response violate this rule?")
    explanation: str = Field(
        default="",
        description="Why/how the rule is violated"
    )
    severity: Literal["low", "medium", "high"] = Field(
        default="medium",
        description="Severity of violation"
    )
    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Confidence in this critique"
    )
    suggestions: list[str] = Field(
        default_factory=list,
        description="Suggested improvements"
    )


class RuleViolation(BaseModel):
    """Record of a rule violation."""
    model_config = ConfigDict(validate_assignment=True)

    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique violation ID")
    rule_id: str = Field(..., description="ID of the violated rule")
    response_text: str = Field(..., description="The response that violated the rule")
    response_type: ResponseType = Field(default=ResponseType.GENERAL)
    critique: Critique = Field(..., description="The critique that identified the violation")
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    resolved: bool = Field(default=False, description="Has this violation been addressed?")
    revision_attempt: int = Field(default=0, description="Number of revision attempts")


class ProposedRuleChange(BaseModel):
    """Proposed change to rules based on learning."""
    model_config = ConfigDict(validate_assignment=True)

    id: str = Field(default_factory=lambda: str(uuid4()))
    change_type: Literal["add", "modify", "remove"] = Field(...)
    rule: LearningRule | SoftRule = Field(..., description="The rule being added/modified")
    rationale: str = Field(..., description="Why this change improves the system")
    based_on_failures: list[str] = Field(
        default_factory=list,
        description="Rule IDs or task UUIDs this is based on"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    status: Literal["proposed", "testing", "approved", "rejected"] = Field(
        default="proposed"
    )
    test_results: dict[str, Any] = Field(
        default_factory=dict,
        description="A/B test results {baseline_score, candidate_score, improvement_pct}"
    )
